### ISSUE TITLE
setDiagnosticsOptions no longer works after worker loaded

### ISSUE THREAD

**Issue by patrickshipe** [remcohaszing/monaco-yaml#105]
It seems that somewhere between monaco-yaml version 3 and 3.2, calling `setDiagnosticsOptions` to change schemas no longer works - the schemas seem frozen to what they were when the worker was first loaded. The options change, but it looks like a no-op – we don't try to load any new schemas. It seems to work in Monaco's JSON plugin just fine (if I call `setDiagnosticsOptions` with a changed schema, it takes effect even for an active Monaco editor).

I tried digging around to find out what is causing this, but it looks like the code changed significantly from 3.0 to 3.2 - any thoughts?

**Comment by patrickshipe** [comment]
@remcohaszing it seems that this PR broke this: https://github.com/remcohaszing/monaco-yaml/pull/99

The JSON worker does the same thing - when the diagnostics options change, we must kill the worker so it restarts with the right options (e.g. schemas). Since we removed this handler, the worker never stops and the changes to not take effect. I added logging to the `stopWorker` handler in the `monaco-yaml` 3.0 and confirmed that this callback is called when I update schemas with `setDiagnosticsOptions`.

**Comment by patrickshipe** [comment]
It seems that "unloading a language" is different from _restarting the worker when settings change_  - since this event chain is being fired from within the plugin when `setDiagnosticsOptions` is called.

**Comment by patrickshipe** [comment]
Sorry for the repeat comments - I put a PR together to restore this, but I do not have permissions in this repo. Happy to share if you would like!

**Comment by remcohaszing** [comment]
Hi @patrickshipe. Thanks for identifying and diagnosing this problem. I think I found the problem as well, but I want to give you a chance to propose your fix. :)

In order to make a change in a repository on GitHub you don’t have permission on, you’ll need to:

- fork it
- clone your fork
- create a new branch
- make changes to your cloned fork
- push the branch to your fork
- make a pull request from your fork to this repository

For more info see the [GitHub’s _Fork a repo_](https://docs.github.com/en/get-started/quickstart/fork-a-repo)

I’m looking forward to your fix!

**Comment by patrickshipe** [comment]
Thank you for the tips @remcohaszing  - first time using GitHub to contribute to an outside project! PR created: https://github.com/remcohaszing/monaco-yaml/pull/109
