### ISSUE TITLE
Provide option to hide `Source` information in schema validation

### ISSUE THREAD

**Issue by domsew** [remcohaszing/monaco-yaml#143]
monaco-yaml displays information about `Source`, like in the picture
![image](https://user-images.githubusercontent.com/17526389/143255883-72e97646-e4a5-4eea-9867-accff3e612fb.png)

It would be great if application had option to hide this information in config. In monaco-editor JSON validation information about `Source` is not displayed by default.

**Comment by remcohaszing** [comment]
Unfortunately this is [hardcoded](https://github.com/redhat-developer/yaml-language-server/blob/47ba49ba447a2ee6e449e49df456f7b61228c043/src/languageservice/services/yamlHover.ts#L144-L146) in `yaml-language-server`, so `monaco-yaml` has no control over this.

It looks like it’s not displayed if no schema url is specified. You can try if that works.

Since this is out of control of `monaco-yaml`, I’m going to close this issue.
