### ISSUE TITLE
model.getModeId is not a function

### ISSUE THREAD

**Issue by johngeorgewright** [remcohaszing/monaco-yaml#146]
It seems there was a breaking change between `monaco-editor` versions `0.22.3` & `0.31.1`. Using `monaco-yaml` with the latest version of `monaco-editor` will result in an immediate error; `model.getModeId is not a function`.

This means that the `peerDependency` range is currently suggesting an incompatible version of `monaco-editor`.

**Comment by remcohaszing** [comment]
Thanks for reporting! This has been fixed in `4.0.0-alpha.0`. This is a major release, because it breaks compatibility with older versions of monaco editor.

```
npm install monaco-yaml@4.0.0-alpha.0
```

As of `4.0.0-alpha.1` there are going to be more breaking changes, but `4.0.0-alpha.0` behaves the same except for support of newer versions of monaco editor.
