### ISSUE TITLE
Incompatibility with monaco-editor >=0.32.0

### ISSUE THREAD

**Issue by domsew** [remcohaszing/monaco-yaml#162]
Hello, monaco-editor introduced a breaking change in version 0.32.0, by changing paths to some files (see [commit](https://github.com/microsoft/monaco-editor/commit/91edee579195dbc61ef05bd31e653be0aff50a1d)). It causes, that bundlers don't provide correct output (silent error). To solve this problem, we need to bump monaco-editor version in v4.0.0-alpha.2 release.

**Comment by remcohaszing** [comment]
Thanks for the heads up!

The main reason this project uses `monaco-editor@0.31.1` is because `monaco-editor@0.32.0` broke how the demo example creates breadcrumbs.

However, I have been using `monaco-yaml@alpha.1` together with `monaco-editor@0.33.0` without any problems in another project. Could you elaborate the what issue you’ve run into?
