### ISSUE TITLE
Apply Monaco YAML validation schema on specific Monaco editor instances

### ISSUE THREAD

**Issue by amir2mi** [remcohaszing/monaco-yaml#214]
I'm using Monaco with `react-monaco-editor` and `monaco-editor-webpack-plugin` in my Next.js application.
I searched for this but could not figure it out, **how to apply Monaco YAML validation schema on specific Monaco instances**. By instance, I mean every time I use Monaco editor component, for example in my app I have multiple editors and each of them need their own set of rules to be validated.

The solution I found to apply YAML schema with Monaco YAML was [mentioned here](https://github.com/remcohaszing/monaco-yaml/issues/98#issuecomment-907815546), I did define a schema with `fileMatch: ["*"]`, obviously, it applies the schema to any editor with YAML language.
I am wondering if it is possible to have multiple schemas for Monaco YAML and apply them to specific editors.

As a built-in feature, with JSON, it was pretty simple:
```jsx
<MonacoEditor
   {...editorProps}
    editorDidMount={(editor, monaco) => {
      monaco.languages.json.jsonDefaults.setDiagnosticsOptions({
        validate: true,
        schemaValidation: "error",
        schemas: [
          {
            uri: "http://validation/json-key-value-schema.json",
            fileMatch: ["*"],
            schema: jsonValidationSchema,
          },
        ],
      });
  }}
/>
```

In the example above, it just applies the schema for given `monaco` instance by React component, but for YAML as [mentioned here](https://github.com/remcohaszing/monaco-yaml/issues/178#issuecomment-1161856837) it can be now imported from `monaco-yaml` package itself and not available per component creation like `monaco.languages.yaml`.
I tried working around  `fileMatch` and `uri` in schema, but there was not a straightforward solution.

**Comment by remcohaszing** [comment]
First a general tip: avoid words such as  _“obviously”_. It tends to come across rude. What’s obvious to you, may not be obvious to someone else.

It appears that by _“instance”_, you mean instance of a Monaco `IStandaloneCodeEditor` (the `editor` variable). This is abstracted away by `<MonacoEditor />`

The problem here is that `react-monaco-editor` gives you the false impression that `monaco` is something scoped to your React component. Your code is equivalent to:

```jsx
import * as monaco from 'monaco-editor'

<MonacoEditor
  {...editorProps}
  editorDidMount={(editor) => {
    monaco.languages.json.jsonDefaults.setDiagnosticsOptions({
      validate: true,
      schemaValidation: "error",
      schemas: [
        {
          uri: "http://validation/json-key-value-schema.json",
          fileMatch: ["*"],
          schema: jsonValidationSchema,
        },
      ],
    });
  }}
/>
```

`monaco-yaml` works pretty much the same. You can specify:

```jsx
import { setDiagnosticsOptions } from 'monaco-yaml'

<MonacoEditor
  {...editorProps}
  editorDidMount={(editor) => {
    setDiagnosticsOptions({
      validate: true,
      schemas: [
        {
          uri: "http://validation/json-key-value-schema.json",
          fileMatch: ["*"],
          schema: jsonValidationSchema,
        },
      ],
    });
  }}
/>
```

I don’t now the project you’re working on, but typically you should use proper names for your model, and use a `fileMatch` that matches your model more specifically.

There isn’t really good Monaco editor information on the basic concepts. I tried to address this in #4087, please have a look there.

> I am wondering if it is possible to have multiple schemas for Monaco YAML and apply them to specific editors.

To directly answer this question: No. The features `monaco-yaml` provides apply to models, not editors.

**Comment by amir2mi** [comment]
Sorry for poorly chosen words, it was not intentional, and thanks for the tip :))
The problem was my misunderstanding as you told that the `monaco` that I get there from React component is actually `import * as monaco from 'monaco-editor'` so the JSON schema validation that I add also applies to all editors!
Thanks for the PR and great job on maintaining the project, cheers!
