### ISSUE TITLE
Question: how to integrate with ngx-monaco-editor-v2

### ISSUE THREAD

**Issue by victor314159** [remcohaszing/monaco-yaml#244]
Hi,
I'm trying to integrate this module with [ngx-monaco-editor-v2](https://github.com/miki995/ngx-monaco-editor-v2)

I've written a SO question because I am not able to make [monaco-yaml](https://github.com/remcohaszing/monaco-yaml) work.

See here:
https://stackoverflow.com/questions/78884711/monaco-yaml-integration-with-ngx-monaco-editor-v2

Could you please give me guidance on what should I change?

Thanks

**Comment by remcohaszing** [comment]
Hi Viktor :wave: 

I’m not familiar with `ngx-monaco-editor-v2` and haven’t used Angular since Angular 2. So I’m not familiar with the build process. I see `ngx-monaco-editor-v2` uses [unsafe JavaScript](https://github.com/miki995/ngx-monaco-editor-v2/blob/master/projects/editor/src/lib/base-editor.ts#L91-L111) to load Monaco editor form a CDN. I strongly recommend against that. I suggest you replace `ngx-monaco-editor-v2` with [`monaco-editor`](https://www.npmjs.com/package/monaco-editor) directly.

One thing I that I do notice is wrong is that you use `type: 'module'` for the worker creation. You shouldn’t specify that.

I also suggest you make JSON support work with `MonacoEnvironment`, then focus on integrating `monaco-yaml`.
