### ISSUE TITLE
Custom format

### ISSUE THREAD

**Issue by abemedia** [remcohaszing/monaco-yaml#43]
Our schema uses custom [formats](https://json-schema.org/understanding-json-schema/reference/string.html#format) and those errors aren't picked up until server-side validation on saving.

It would be really great if one could register validation functions for custom formats to do the same validation on the front-end as is currently occurring on the server.

**Comment by remcohaszing** [comment]
I think this would be a great feature! I imagine it works something like this:

**Type definition**:

```ts
interface DiagnosticsOptions {
  // …

  /**
   * Validate a value for a JSON schema format.
   *
   * @param format The format to validate the value against.
   * @param value The value to validate,
   * @param path The path to the value to validate
   * @returns A boolean indicating whether or not the value conforms to the format.
   */
  async validateFormat(format: string, value: number | string, path: (number | string)[]): Promisable<boolean>;
}
```

**Implementation example**:

```ts
import { setDiagnosticsOptions } from 'monaco-yaml'

setDiagnosticsOptions() {
  async validateFormat(format, value, path) {
    switch (format) {
      case 'pizza-topping':
        return value !== 'pineapple';
      default:
        return true;
    }
  }
}
```

For `monaco-yaml` to support custom formats, this needs to be supported by [`yaml-language-server`](https://github.com/redhat-developer/yaml-language-server). In turn, for `yaml-language-server` to support this, this needs to be supported by [`json-language-service`](https://github.com/microsoft/vscode-json-languageservice).

Support for format validation is implemented in [`jsonParser.ts`](
https://github.com/microsoft/vscode-json-languageservice/blob/65f660bb0db367a4df4141d07dabb2f1fc71d9d5/src/parser/jsonParser.ts#L658-L695). Since `monaco-yaml` uses asynchronous communication using web workers, the first step would be to implement custom asynchronous validation there.

**Comment by remcohaszing** [comment]
I’m going to closes this as _won’t fix_. I will add support if it’s supported upstream
