### ISSUE TITLE
Non-relative import for unknown module: monaco-editor/esm/vs/editor/editor.worker

### ISSUE THREAD

**Issue by joeveiga** [remcohaszing/monaco-yaml#50]
I've been trying to add this plugin for a while without success. Is there something I'm missing here?
Thanks.

## Steps to reproduce

Clone latest `monaco-editor` (0.23.0):

```
$ git clone https://github.com/microsoft/monaco-editor.git
$ cd monaco-editor
```

Install the package:

`$ npm i -D monaco-yaml`

Add the plugin to my `metadata.js` file:

```js
{
  name: "monaco-yaml",
  contrib: "vs/language/yaml/monaco.contribution",
  modulePrefix: "vs/language/yaml",
  paths: {
    src: "/monaco-yaml/lib/dev",
    "npm/dev": "node_modules/monaco-yaml/lib/dev",
    "npm/min": "node_modules/monaco-yaml/lib/min",
    esm: "node_modules/monaco-yaml/lib/esm",
  },
}
```
Build it:

`$ npm run release`

I get the following error:

`Non-relative import for unknown module: monaco-editor/esm/vs/editor/editor.worker in /Users/jose.veiga/Projects/monaco-editor/node_modules/monaco-yaml/lib/esm/yaml.worker.js`

## What I've tried

I tried commenting out the `esm` config, since I'm only gonna be using the `dev` or `min` version anyway:

```js
{
  name: "monaco-yaml",
  contrib: "vs/language/yaml/monaco.contribution",
  modulePrefix: "vs/language/yaml",
  paths: {
    src: "/monaco-yaml/lib/dev",
    "npm/dev": "node_modules/monaco-yaml/lib/dev",
    "npm/min": "node_modules/monaco-yaml/lib/min",
    // esm: "node_modules/monaco-yaml/lib/esm",
  },
}
```

This works (the `release` script finishes successfully), however, when I copy the artifacts into my Angular web app...

```
$ rm -rf <path-to-web-app>/src/assets/monaco/vs
$ cp -R ./monaco-editor/release/dev/vs <path-to-web-app>/src/assets/monaco/
```
...and refresh, I get this error in the browser:

`Uncaught ReferenceError: monaco is not defined`

**Comment by remcohaszing** [comment]
The script you found is used to **build** the `monaco-editor` package. This package **uses** the `monaco-editor` package. Also I removed UMD support, because it didn’t work.

Please have a look at the [examples](https://github.com/remcohaszing/monaco-yaml/tree/main/examples/webpack-worker-loader) to see how to use this package.

**Comment by joeveiga** [comment]
@remcohaszing I see. My understanding was this was a plugin for monaco-editor that had to be bundled with the editor itself, following the steps in their [CONTRIBUTING](https://github.com/microsoft/monaco-editor/blob/main/CONTRIBUTING.md) guide. Is there a way I'd be able to use this package in that manner? (perhaps with some minor modifications/tweaks). I'd appreciate some guidance, thanks!

**Comment by remcohaszing** [comment]
As of `monaco-editor` 22 they dropped support for the global `monaco`. This means for this package I had to choose to either support `monaco-editor` or `monaco-editor-core` (microsoft/monaco-editor#2451). I chose `monaco-editor`. This means `monaco-yaml` depends on the build output of `monaco-editor`.

Also I dropped support for UMD, because as far as I’m aware, the UMD build has been broken for a long time. Also I believe ESM is the future of JavaScript modules.

This package can be used like any other package from npm. Simply install it using `npm install monaco-editor monaco-yaml`. See the [webpack example](https://github.com/remcohaszing/monaco-yaml/tree/main/examples/webpack) as a reference.

I’m also open to examples using other bundlers if you’re interested.

---

> Is there a way I'd be able to use this package in that manner? (perhaps with some minor modifications/tweaks). I'd appreciate some guidance, thanks!

If you really want to use it in that manner, you could try to use version 2.x of `monaco-yaml`. Although I recommend to just use `npm install` instead of a custom monaco build.
