### ISSUE TITLE
how use the isKubernetes diagnostic option

### ISSUE THREAD

**Issue by olensmar** [remcohaszing/monaco-yaml#54]
Hello!

I'm trying to understand what the isKubernetes property on the DiagnosticsOptions interface does - if/how to use it... I couldn't find anything helpful here or in the language-server repo - can anyone provide some insight / point me to somewhere I can learn? 

thanks in advance!

/Ole

**Comment by remcohaszing** [comment]
In order to understand, it’s important to understand `yaml-language-server` consists of 2 parts:

1. The YAML language service
2. The YAML language server

`monaco-yaml` only uses the language service part. From what I can tell, the `isKubernetes` option uses slightly different algorithms for handling `oneOf` schemas. These are supposed to handle Kubernetes resources, which basically have to adhere to one of **many** sub schemas, in a more user friendly manner.

For completeness sake I’ll also explain the language server part. This part turns a JSON schema URI of `'kubernetes'` to `'https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.20.5-standalone-strict/all.json'`. This is a big JSON schema which defines many Kubernetes related resources. Unfortunately this JSON schema doesn’t appear to work with `monaco-yaml` our of the box.

Beware I might be wrong about some things. I based this on some inspection I did on `yaml-language-server` myself.

I hope this helps. :)

**Comment by olensmar** [comment]
Thanks @remcohaszing for taking your time to answer - this definitely helps!
