### ISSUE TITLE
Unable to parse content from '/undefined': Parse error at offset 0

### ISSUE THREAD

**Issue by javanoclaw** [remcohaszing/monaco-yaml#62]
Unable to parse content from '/undefined': Parse error at offset 0 when i set enableSchemaRequest false

Here is my code:
```js
import { editor } from 'monaco-editor/esm/vs/editor/editor.api';
import { setDiagnosticsOptions } from 'monaco-yaml';
import 'monaco-editor';
import yamlWorkerUrl from 'worker-plugin/loader?name=yaml&esModule!monaco-yaml/lib/esm/yaml.worker';

window.MonacoEnvironment = {
  getWorkerUrl() {
    return yamlWorkerUrl;
  }
};

setDiagnosticsOptions({
  validate: true,
  enableSchemaRequest: false,
  hover: true,
  completion: true,
  schemas: [
    {
      fileMatch: ['*'],
      schema: {
        type: 'object',
        properties: {
          p1: {
            enum: ['v1', 'v2'],
          },
        },
      },
    },
    {
      schema: {
        type: 'object',
        properties: {
          q1: {
            enum: ['x1', 'x2'],
          },
        },
      },
    },
  ],
});
const monaco = editor.create(document.getElementById('editor'), {
        value: 'p1: ',
        language: 'yaml',
});
 console.log(monaco);
}
```

**Comment by remcohaszing** [comment]
I’m not familiar with `worker-plugin`. I think the following should help you troubleshoot:

- Could you verify `yamlWorkerUrl` is defined by logging it to the console?
- Is `worker-plugin` configured in your webpack configuration?
- No only `monaco-yaml` needs to be handled by `MonacoEnvironment.getWorkerUrl()`, but also any other workers created by Monaco.
  https://github.com/pengx17/monaco-yaml/blob/090302534ae205d3a7163375bf211be5e8dd5eda/examples/webpack/src/index.js#L10-L17
  In your case this should be something like:
  ```ts
  import editorWorkerUrl from 'worker-plugin/loader?name=yaml&esModule!onaco-editor/esm/vs/editor/editor.worker';
  import yamlWorkerUrl from 'worker-plugin/loader?name=yaml&esModule!monaco-yaml/lib/esm/yaml.worker';

  window.MonacoEnvironment = {
    getWorkerUrl(moduleId, label) {
      if (label === 'yaml') {
        return yamlWorkerUrl;
      }
      return editorWorkerUrl;
    }
  };
  ```

One additional tip: If you `import 'monaco-editor'` to get all features, you may as well `import { editor } from 'monaco-editor'` instead of from `monaco-editor/esm/vs/editor/editor.api`.

**Comment by remcohaszing** [comment]
I’m going to close this issue, because Webpack 5 supports web workers out of the box without the need for any special loaders or plugins. Please see the updated example.

https://github.com/remcohaszing/monaco-yaml/blob/3094ebef91bc348b8a8efff70488163934f833b7/examples/webpack/src/index.js#L10-L27
