### ISSUE TITLE
Build without prettier

### ISSUE THREAD

**Issue by abeMedia** [remcohaszing/monaco-yaml#63]
I'm not using formatting, however prettier is included in the final webpack bundle, making much larger than it needs to be.

Is there any way to not include prettier?

**Comment by remcohaszing** [comment]
I recently started maintaining this repository, so there are still some things I’m not 100% familiar with in this repository.

The package is built using [`monaco-plugin-helpers`](https://github.com/alexdima/monaco-plugin-helpers), an undocumented built tool specifically for monaco plugins. The build script for `monaco-yaml` can be found [here](https://github.com/remcohaszing/monaco-yaml/blob/main/scripts/bundle-esm.js). I don’t think it’s possible to exclude prettier.

However, I’m interested in replacing the build script with a more conventional build tool, such as [`rollup`](https://rollupjs.org). I think this opens up the possibility to exclude Prettier from the build, making it a regular dependency. You could then stub out Prettier in your own build chain.

Any help would be greatly appreciated.

Please let me know if you’re interested in helping out! Otherwise I’ll get to it when I get to it. :shrug:

**Comment by remcohaszing** [comment]
I’m looking into rollup right now!

**Comment by abeMedia** [comment]
To be honest I don't know how much help I can be with that. Never used rollup as I'm more of a webpack guy myself...

**Comment by remcohaszing** [comment]
I’m fine with using Webpack as well. I just though rollup is more appropriate for libraries, although I have no prior experience with rollup either. :shrug: 

I don’t have time for this in the upcoming few weeks, but I’m fine with a Webpack implemenation as well if you’re willing to give it a shot. I updated the example to Webpack 5 in #65.

Please let me know if you’re interested in trying and need any help. :)
